# Copyright (c) 2025 Eclipse Foundation.
# 
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: MIT


# Commented sections are optional. Uncomment them if you want to include them in config

publisher: # General publisher info section
    author: "Author name"
    company: "Author company"

# How to build and sign package
build:
    os: linux
    arch: x86
    symlinks: copy
    sign_pkcs12: aos-user-sp.p12
    # context: string, optional

# Information about publishing process (URI, cert, etc)
publish:
    url: aoscloud.io
    service_uid: 54d0b98c-e986-4bec-b065-bef119b9aa0f
    tls_pkcs12: aos-user-sp.p12
    version: "0.9.92"

# Service configuration
configuration:
    state:
        filename: state.dat
        required: False

    # Startup command
    # cmd: python3 -u kuksa_test_client.py
    cmd: bash run.sh

    layers:
        - "aos-pylibs-layer"

    resources:
        - kuksa

    # Service working dir
    workingDir: '/'

    # Quotas assigned to service
    quotas:
        cpu: 100
        mem: 256MB
        state: 128KB
        storage: 128MB
        upload_speed: 1MB
        download_speed: 1MB
        upload: 512MB
        download: 512MB
        temp: 128KB

# For additional information please visit the page:
# https://docs.aoscloud.io/bin/view/Home/Architecture/General/Data%20formats/Service%20formats/Containers%20configuration%20file/
